In [1]:
import numpy as np
#numpy stands for numerical python

In [2]:
# one d array -> vector
arr1d = np.array([10,20,23,20,210,2,12,10])
print(arr1d)

[ 10  20  23  20 210   2  12  10]


In [3]:
# two d array -> matrix
arr2d = np.array([[10,20,30],
                  [40,50,60]])
print(arr2d)

[[10 20 30]
 [40 50 60]]


In [4]:
#array with defaults values

#zero array or matrix
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#array with one
one = np.ones((2,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#array with given numbers
full = np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [7]:
# identity matrix
idm = np.eye(4)
print(idm)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## creating sequence of number

In [8]:
arr =  np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


# proerties and operation 

In [9]:
#creating array
arr = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

In [10]:
arr.shape

(3, 4)

In [11]:
#give num of element present in array
arr.size

12

In [12]:
#num of dim
arr.ndim

2

In [13]:
#3d array
np.array([[[1,2],[3,4],[5,6],[7,8]]])

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [14]:
#type of data in array
arr.dtype

dtype('int64')

In [15]:
#change datatype to convert
arr1 = arr.astype("str")
arr1

array([['10', '20', '30', '40'],
       ['50', '60', '70', '80'],
       ['90', '100', '110', '120']], dtype='<U21')

In [16]:
arr1.dtype

dtype('<U21')

In [17]:
#operation
print(arr)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [18]:
print(arr+40)

[[ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]


In [19]:
#aggregation function

In [20]:
np.sum(arr)  #sum

np.int64(780)

In [21]:
np.mean(arr) #average 

np.float64(65.0)

In [22]:
np.min(arr)  #min

np.int64(10)

In [23]:
np.max(arr)    #max

np.int64(120)

In [24]:
np.std(arr)    #standard deviation

np.float64(34.52052529534663)

In [25]:
np.var(arr)   # variance

np.float64(1191.6666666666667)

# indexing(access element) and slicing(subset of array)

In [26]:
print(arr2d)

[[10 20 30]
 [40 50 60]]


In [27]:
arr2d[0,1]

np.int64(20)

In [39]:
#slicing and indexing and slicing of 1d array same as list indexing and slicing
print(arr)

print(arr[:2,1:])

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[20 30 40]
 [60 70 80]]


In [31]:
#boolean filtering
arr2d[arr2d>20]

array([30, 40, 50, 60])

# reshape array

In [40]:
arr1d

array([ 10,  20,  23,  20, 210,   2,  12,  10])

In [43]:
arr1d.reshape(4,2)  # provide only a view not change or create new array

array([[ 10,  20],
       [ 23,  20],
       [210,   2],
       [ 12,  10]])

In [44]:
arr1d

array([ 10,  20,  23,  20, 210,   2,  12,  10])

In [45]:
# convert multi dim array in 1d
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [49]:
arr.ravel() #return view means memory efficient

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [50]:
arr.flatten() # return from copy 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

# array modification